<?php

return [
    [
        "id" => "1",
        "name" => "Windsor Market Square",
        "type" => "Market",
        "address" => "2109 Ottawa St",
        "postal" => "1212",
        "phone" => "+ 1515-253-7374",
        "opens_at" => "10:00",
        "closes_at" => "16:00",
        "starts_from" => "Mon",
        "ends_on" => "Fri",
        "menu" => [],
        "specials_available" => [],
        "prices" => [],
    ],
    [
        "id" => "2",
        "name" => "The City Market",
        "type" => "Farmers' market",
        "address" => "2109 Ottawa St",
        "postal" => "1213",
        "phone" => "+ 1515-253-7374",
        "opens_at" => "09:00",
        "closes_at" => "16:00",
        "starts_from" => "Mon",
        "ends_on" => "Fri",
        "menu" => [],
        "specials_available" => [],
        "prices" => [],
    ],
    [
        "id" => "3",
        "name" => "Downtown Windsor Farmers Market",
        "type" => "Farmers' market",
        "address" => "2109 Ottawa St",
        "postal" => "1214",
        "phone" => "+ 1515-253-7374",
        "opens_at" => "08:00",
        "closes_at" => "15:00",
        "starts_from" => "Mon",
        "ends_on" => "Fri",
        "menu" => [],
        "specials_available" => [],
        "prices" => [],
    ],
    [
        "id" => "4",
        "name" => "Windsor Food Distributors",
        "type" => "Farmers' market",
        "address" => "1075 Crawford Ave",
        "postal" => "1215",
        "phone" => "+1 519-915-6636",
        "opens_at" => "09:00",
        "closes_at" => "16:00",
        "starts_from" => "Mon",
        "ends_on" => "Fri",
        "menu" => [],
        "specials_available" => [],
        "prices" => [],
    ],
    [
        "id" => "5",
        "name" => "Food products supplier",
        "type" => "Farmers' market",
        "address" => "2601 Wyandotte St E",
        "postal" => "1216",
        "phone" => "+1 519-252-5414",
        "opens_at" => "08:00",
        "closes_at" => "16:00",
        "starts_from" => "Mon",
        "ends_on" => "Fri",
        "menu" => [],
        "specials_available" => [],
        "prices" => [],
    ]
];


